CREATE TABLE `edu_course` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(200) NOT NULL COMMENT '课程名称',
  `image_url` varchar(200) DEFAULT NULL COMMENT '课程图片URL',
  `major_id` bigint DEFAULT NULL COMMENT '所属专业ID',
  `course_type` tinyint NOT NULL DEFAULT '0' COMMENT '课程类型 0:学练考 1:试题库',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1:启用 0:禁用',
  `recommended` tinyint NOT NULL DEFAULT '0' COMMENT '推荐 1:是 0:否',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `learning_objectives` text COMMENT '学习目标（富文本）',
  `introduction` text COMMENT '简介（富文本）',
  `months_required` int DEFAULT NULL COMMENT '需要学习月数',
  `total_price` decimal(10,2) DEFAULT NULL COMMENT '总价格',
  `is_free` tinyint NOT NULL DEFAULT '0' COMMENT '是否完全免费 1:是 0:否',
  `is_free_limited` tinyint NOT NULL DEFAULT '0' COMMENT '是否限时免费 1:是 0:否',
  `free_start_time` datetime DEFAULT NULL COMMENT '限时免费开始时间',
  `free_end_time` datetime DEFAULT NULL COMMENT '限时免费结束时间',
  `allow_trial` tinyint NOT NULL DEFAULT '0' COMMENT '是否允许试学 1:是 0:否',
  `teacher` varchar(100) DEFAULT NULL COMMENT '教师',
  `student_count` int NOT NULL DEFAULT '0' COMMENT '学员数',
  `view_count` int NOT NULL DEFAULT '0' COMMENT '浏览数',
  `chapter_count` int NOT NULL DEFAULT '0' COMMENT '章节数',
  `question_count` int NOT NULL DEFAULT '0' COMMENT '试题数',
  `exam_count` int NOT NULL DEFAULT '0' COMMENT '试卷数',
  `video_count` int NOT NULL DEFAULT '0' COMMENT '视频数',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0:正常 1:已删除',
  PRIMARY KEY (`id`),
  KEY `idx_major_id` (`major_id`),
  KEY `idx_status` (`status`),
  KEY `idx_recommended` (`recommended`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='课程表';
