CREATE TABLE `edu_student` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `avatar_url` varchar(500) DEFAULT NULL COMMENT '头像URL',
  `account` varchar(50) NOT NULL COMMENT '账号',
  `password` varchar(200) NOT NULL COMMENT '密码（BCrypt加密）',
  `name` varchar(50) DEFAULT NULL COMMENT '姓名',
  `pinyin_abbr` varchar(50) DEFAULT NULL COMMENT '拼音缩写',
  `student_no` varchar(50) DEFAULT NULL COMMENT '学员编号',
  `group_id` bigint DEFAULT NULL COMMENT '学员组ID',
  `gender` tinyint DEFAULT '0' COMMENT '性别 1:男 2:女 0:未知',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `phone` varchar(20) DEFAULT NULL COMMENT '移动电话',
  `phone_public` tinyint DEFAULT '1' COMMENT '移动电话是否公开 1:是 0:否',
  `fixed_phone` varchar(20) DEFAULT NULL COMMENT '固定电话',
  `fixed_phone_public` tinyint DEFAULT '1' COMMENT '固定电话是否公开 1:是 0:否',
  `email` varchar(100) DEFAULT NULL COMMENT '电子邮箱',
  `qq` varchar(20) DEFAULT NULL COMMENT 'QQ',
  `wechat` varchar(50) DEFAULT NULL COMMENT '微信',
  `address` varchar(200) DEFAULT NULL COMMENT '住址',
  `mailing_address` varchar(200) DEFAULT NULL COMMENT '通讯地址',
  `zip_code` varchar(10) DEFAULT NULL COMMENT '邮编',
  `emergency_contact` varchar(50) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(20) DEFAULT NULL COMMENT '紧急电话',
  `birth_date` date DEFAULT NULL COMMENT '出生年月',
  `education` varchar(50) DEFAULT NULL COMMENT '学历',
  `major` varchar(100) DEFAULT NULL COMMENT '专业',
  `native_place` varchar(100) DEFAULT NULL COMMENT '籍贯',
  `school` varchar(200) DEFAULT NULL COMMENT '学校',
  `nationality` varchar(50) DEFAULT NULL COMMENT '民族',
  `signature` varchar(500) DEFAULT NULL COMMENT '签名',
  `bio` text COMMENT '个人介绍（富文本）',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1:启用 0:禁用',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0:正常 1:已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account` (`account`),
  UNIQUE KEY `uk_student_no` (`student_no`),
  KEY `idx_phone` (`phone`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学员信息表';
