CREATE TABLE `edu_major` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '上级专业ID（0=顶级）',
  `name` varchar(100) NOT NULL COMMENT '专业名称',
  `alias` varchar(100) DEFAULT NULL COMMENT '别名',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1:启用 0:禁用',
  `recommended` tinyint NOT NULL DEFAULT '0' COMMENT '推荐 1:是 0:否',
  `description` varchar(500) DEFAULT NULL COMMENT '说明',
  `image_url` varchar(200) DEFAULT NULL COMMENT '展示图片URL',
  `detail` text COMMENT '详情（富文本）',
  `sort` int NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0:正常 1:已删除',
  PRIMARY KEY (`id`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='专业表';
