-- 积分兑换订单表
CREATE TABLE edu_points_order (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    order_no VARCHAR(32) NOT NULL COMMENT '订单编号',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    product_name VARCHAR(100) NOT NULL COMMENT '商品名称',
    product_type TINYINT NOT NULL COMMENT '商品类型: 1=实物 2=学习卡',
    required_points INT NOT NULL COMMENT '消耗积分',
    exchange_type TINYINT NOT NULL COMMENT '兑换方式: 1=线下自取 2=邮寄到家',
    exchange_code VARCHAR(16) DEFAULT NULL COMMENT '兑换码',
    card_instance_id BIGINT DEFAULT NULL COMMENT '学习卡实例ID',
    card_no VARCHAR(50) DEFAULT NULL COMMENT '学习卡卡号',
    card_secret VARCHAR(20) DEFAULT NULL COMMENT '学习卡密钥',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态: 0=待处理 1=已发货 2=已签收 3=已核销 4=已取消',
    receiver_name VARCHAR(50) DEFAULT NULL,
    receiver_phone VARCHAR(20) DEFAULT NULL,
    receiver_address VARCHAR(500) DEFAULT NULL,
    express_company VARCHAR(50) DEFAULT NULL,
    express_no VARCHAR(50) DEFAULT NULL,
    ship_time DATETIME DEFAULT NULL,
    receive_time DATETIME DEFAULT NULL,
    verify_time DATETIME DEFAULT NULL,
    verify_by BIGINT DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_user_id (user_id),
    INDEX idx_order_no (order_no),
    INDEX idx_exchange_code (exchange_code),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分兑换订单表';
