server:
  port: 8001
  servlet:
    context-path: /api

spring:
  application:
    name: learn-system
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

jwt:
  access-expiration: 1800000
  refresh-expiration: 604800000
