spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:8.137.54.208}:${MYSQL_PORT:3306}/learn_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:xxwh@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:8.137.54.208}
      port: ${REDIS_PORT:6379}
      database: 0
      password: ${REDIS_PASSWORD:xxwh@123}

jwt:
  secret: ${JWT_SECRET:/fpXjBn1LuNfzSZADKEP6x8scSsUIrg2lMXLnJZj3W4=}

# 七牛云配置
qiniu:
  access-key: bTvYj1nirulPnfusmg-vG-sAGzSMZUbGbCvBRGdW
  secret-key: qogThvZIYKj9ZMheSBPmbYrm9fPVMzv2Okh_4BXv
  bucket: yub-learn-system
  domain: http://tgnxos2ym.hn-bkt.clouddn.com

# AI助教配置
ai:
  api-key: ${AI_API_KEY:tp-c2ajmdwscpit7ihqkxcyaqiwkrjpmxfnal2yob2ygvtztxxf}
  base-url: ${AI_BASE_URL:https://token-plan-cn.xiaomimimo.com/v1}
  model: ${AI_MODEL:mimo-v2.5}
  max-tokens: 200000
  timeout: 60
